FROM dpage/pgadmin4

# Set environment variables
ENV PGADMIN_DEFAULT_EMAIL=admin@example.com
ENV PGADMIN_DEFAULT_PASSWORD=admin

# Copy server configuration (optional)
COPY pgadmin-servers.json /pgadmin4/servers.json